import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

class AppLocalizations {
  final Locale locale;

  const AppLocalizations(this.locale);

  static const supportedLocales = [
    Locale('en'),
    Locale('om'),
    Locale('am'),
  ];

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final result = Localizations.of<AppLocalizations>(context, AppLocalizations);
    if (result == null) {
      throw FlutterError('AppLocalizations not found in the widget tree.');
    }
    return result;
  }

  String text(String key) {
    final languageCode = supportedLocales.any(
      (supportedLocale) => supportedLocale.languageCode == locale.languageCode,
    )
        ? locale.languageCode
        : 'en';
    return _localizedValues[languageCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appName': 'Picverse',
      'welcomeBack': 'Welcome Back',
      'signInContinue': 'Sign in to continue to Picverse',
      'emailAddress': 'Email address',
      'password': 'Password',
      'forgotPassword': 'Forgot Password?',
      'signIn': 'Sign In',
      'or': 'or',
      'continueWithGoogle': 'Continue with Google',
      'dontHaveAccount': "Don't have an account? ",
      'createAccount': 'Create Account',
      'joinAndShare': 'Join Picverse and start sharing',
      'username': 'Username',
      'confirmPassword': 'Confirm Password',
      'agreeTerms': 'I agree to the Terms & Conditions',
      'pleaseAgreeTerms': 'Please agree to the Terms & Conditions',
      'passwordsDoNotMatch': 'Passwords do not match',
      'alreadyHaveAccount': 'Already have an account? ',
      'logOut': 'Log out',
      'lightMode': 'Light Mode',
      'darkMode': 'Dark Mode',
      'systemDefault': 'System Default',
      'tapChangeTheme': 'Tap to change theme',
      'language': 'Language',
      'english': 'English',
      'afaanOromo': 'Afaan Oromo',
      'amharic': 'Amharic',
      'selectLanguage': 'Select language',
      'searchUsers': 'Search users...',
      'searchForUsers': 'Search for users',
      'noUsersFound': 'No users found',
      'filterBy': 'Filter by',
      'all': 'All',
      'hasBio': 'Has bio',
      'hasPhoto': 'Has photo',
      'chats': 'Chats',
      'couldNotLoadChats': 'Could not load chats',
      'noChatsYet': 'No chats yet',
      'startChatHint': 'Open a profile or create a group to start chatting.',
      'sayHello': 'Say hello',
      'createGroupChat': 'Create group chat',
      'groupName': 'Group name',
      'searchPeople': 'Search people',
      'searchForPeopleToAdd': 'Search for people to add',
      'createGroup': 'Create group',
      'passwordResetSent': 'Password reset email sent! Check your inbox.',
      'resetPasswordInstructions': 'Enter your email and we\'ll send you\na link to reset your password',
      'sendResetLink': 'Send Reset Link',
      'backToSignIn': 'Back to Sign In',
      'writeMessage': 'Write a message...',
      'startConversation': 'Start the conversation',
      'notifications': 'Notifications',
      'markAllRead': 'Mark all read',
      'noNotifications': 'No notifications',
      'retry': 'Retry',
      'errorLoadingProfile': 'Error loading profile',
      'profile': 'Profile',
      'editProfile': 'Edit Profile',
      'followers': 'Followers',
      'following': 'Following',
      'posts': 'Posts',
      'theme': 'Theme',
      'settings': 'Settings',
      'openAdminDashboard': 'Open admin dashboard',
      'loadMore': 'Load more',
      'home': 'Home',
      'search': 'Search',
      'post': 'Post',
      'withCaption': 'With caption',
      'withImage': 'With image',
      'connectionsFilter': 'Connections filter',
      'allPeople': 'All people',
      'withBio': 'With bio',
      'withProfilePhoto': 'With profile photo',
    },
    'om': {
      'appName': 'Picverse',
      'welcomeBack': 'Baga nagaan deebiite',
      'signInContinue': 'Picverse itti fufuuf seeni',
      'emailAddress': 'Teessoo email',
      'password': 'Jecha icciitii',
      'forgotPassword': 'Jecha icciitii dagatte?',
      'signIn': 'Seeni',
      'or': 'ykn',
      'continueWithGoogle': 'Google waliin itti fufi',
      'dontHaveAccount': 'Herrega hin qabdu? ',
      'createAccount': 'Herrega uumi',
      'joinAndShare': 'Picverse keessatti hirmaadhuu qoodi',
      'username': 'Maqaa fayyadamaa',
      'confirmPassword': 'Jecha icciitii mirkaneessi',
      'agreeTerms': 'Karoora fi haala irratti walii gala',
      'pleaseAgreeTerms': 'Maaloo haala fi seera irratti walii gali',
      'passwordsDoNotMatch': 'Jechoonni icciitii wal hin gitan',
      'alreadyHaveAccount': 'Herrega qabda? ',
      'logOut': 'Ba’i',
      'lightMode': 'Bifa ifaa',
      'darkMode': 'Bifa dukkanaa',
      'systemDefault': 'Sirna faayaa',
      'tapChangeTheme': 'Bifa jijjiiruuf tuqi',
      'language': 'Afaan',
      'english': 'Ingiliffa',
      'afaanOromo': 'Afaan Oromoo',
      'amharic': 'Amaariffa',
      'selectLanguage': 'Afaan fili',
      'searchUsers': 'Fayyadamtoota barbaadi...',
      'searchForUsers': 'Fayyadamtoota barbaadi',
      'noUsersFound': 'Fayyadamaa hin argamne',
      'filterBy': 'Gara filadhu',
      'all': 'Hunda',
      'hasBio': 'Biiroo qaba',
      'hasPhoto': 'Suuraa qaba',
      'chats': 'Waraabbeewwan',
      'couldNotLoadChats': 'Waraabbeewwan fe’uun hin danda’amne',
      'noChatsYet': 'Waraabbiin hin jiru',
      'startChatHint': 'Profilii bani ykn garee uumi jalqabi',
      'sayHello': 'Akkam jedhi',
      'createGroupChat': 'Waraabbii garee uumi',
      'groupName': 'Maqaa garee',
      'searchPeople': 'Namoota barbaadi',
      'searchForPeopleToAdd': 'Namoota dabaluu barbaadi',
      'createGroup': 'Garee uumi',
      'passwordResetSent': 'Imeelli deebisuu jecha icciitii ergameera! Sanduuqa keessa ilaali.',
      'resetPasswordInstructions': 'Imeela kee galchi, ergamni deebisuu jecha icciitii siif erga.',
      'sendResetLink': 'Xalayaa deebisuu ergi',
      'backToSignIn': 'Deebi\'i seensatti',
      'writeMessage': 'Ergaa barreessi...',
      'startConversation': 'Marii jalqabi',
      'notifications': 'Beeksisa',
      'markAllRead': 'Hundaa dubbisi jechuun mallatessi',
      'noNotifications': 'Beeksisni hin jiru',
      'retry': 'Irra deebi’i',
      'errorLoadingProfile': 'Profilii fe’uun dogoggore',
      'profile': 'Profilii',
      'editProfile': 'Profilii gulaali',
      'followers': 'Hordoftoota',
      'following': 'Hordofta',
      'posts': 'Maxxansoota',
      'theme': 'Bifa',
      'settings': 'Qindaa’ina',
      'openAdminDashboard': 'Daashboordii admin bani',
      'loadMore': 'Dabalataan fe’i',
      'home': 'Mana',
      'search': 'Barbaadi',
      'post': 'Maxxansi',
      'withCaption': 'Yaada qabu',
      'withImage': 'Suuraa qabu',
      'connectionsFilter': 'Filannoo walitti dhufeenyaa',
      'allPeople': 'Namoota hunda',
      'withBio': 'Biiroo qabu',
      'withProfilePhoto': 'Suuraa pirofaayilii qabu',
    },
    'am': {
      'appName': 'ፒክቨርስ',
      'welcomeBack': 'እንኳን ደህና መጡ',
      'signInContinue': 'ወደ ፒክቨርስ ለመቀጠል ይግቡ',
      'emailAddress': 'የኢሜይል አድራሻ',
      'password': 'የይለፍ ቃል',
      'forgotPassword': 'የይለፍ ቃል ረሱ?',
      'signIn': 'ግባ',
      'or': 'ወይም',
      'continueWithGoogle': 'በGoogle ይቀጥሉ',
      'dontHaveAccount': 'መለያ የለዎትም? ',
      'createAccount': 'መለያ ይፍጠሩ',
      'joinAndShare': 'ፒክቨርስን ይቀላቀሉ እና ያጋሩ',
      'username': 'የተጠቃሚ ስም',
      'confirmPassword': 'የይለፍ ቃልን ያረጋግጡ',
      'agreeTerms': 'ከደንቦችና ሁኔታዎች ጋር እስማማለሁ',
      'pleaseAgreeTerms': 'እባክዎ ከደንቦችና ሁኔታዎች ጋር ይስማሙ',
      'passwordsDoNotMatch': 'የይለፍ ቃሎቹ አይመሳሰሉም',
      'alreadyHaveAccount': 'መለያ አለዎት? ',
      'logOut': 'ውጣ',
      'lightMode': 'ብርሃን ሁኔታ',
      'darkMode': 'ጨለማ ሁኔታ',
      'systemDefault': 'የስርዓት ነባሪ',
      'tapChangeTheme': 'ገጽታ ለመቀየር ይንኩ',
      'language': 'ቋንቋ',
      'english': 'እንግሊዝኛ',
      'afaanOromo': 'አፋን ኦሮሞ',
      'amharic': 'አማርኛ',
      'selectLanguage': 'ቋንቋ ይምረጡ',
      'searchUsers': 'ተጠቃሚዎችን ይፈልጉ...',
      'searchForUsers': 'ተጠቃሚዎችን ይፈልጉ',
      'noUsersFound': 'ተጠቃሚ አልተገኘም',
      'filterBy': 'በዚህ ያጣሩ',
      'all': 'ሁሉም',
      'hasBio': 'ባዮ ያለው',
      'hasPhoto': 'ፎቶ ያለው',
      'chats': 'ውይይቶች',
      'couldNotLoadChats': 'ውይይቶች ማስጫን አልተቻለም',
      'noChatsYet': 'እስካሁን ውይይት የለም',
      'startChatHint': 'ውይይት ለመጀመር ፕሮፋይል ይክፈቱ ወይም ቡድን ይፍጠሩ',
      'sayHello': 'ሰላም ይበሉ',
      'createGroupChat': 'የቡድን ውይይት ይፍጠሩ',
      'groupName': 'የቡድን ስም',
      'searchPeople': 'ሰዎችን ይፈልጉ',
      'searchForPeopleToAdd': 'ሰዎችን ለማከል ይፈልጉ',
      'createGroup': 'ቡድን ይፍጠሩ',
      'passwordResetSent': 'የይለፍ ቃል መቀየሪያ ኢሜይል ተልኳል! የገቢ ሳጥንዎን ይመልከቱ።',
      'resetPasswordInstructions': 'ኢሜይልዎን ያስገቡ እና የይለፍ ቃልዎን ለመቀየር አገናኝ እንልክሎታለን',
      'sendResetLink': 'የመቀየሪያ አገናኝ ላክ',
      'backToSignIn': 'ወደ መግቢያ ተመለስ',
      'writeMessage': 'መልዕክት ይጻፉ...',
      'startConversation': 'ውይይቱን ይጀምሩ',
      'notifications': 'ማሳወቂያዎች',
      'markAllRead': 'ሁሉንም እንደተነበበ ምልክት ያድርጉ',
      'noNotifications': 'ማሳወቂያ የለም',
      'retry': 'እንደገና ይሞክሩ',
      'errorLoadingProfile': 'ፕሮፋይል ማስጫን ተሳክቷል',
      'profile': 'ፕሮፋይል',
      'editProfile': 'ፕሮፋይል አርትዕ',
      'followers': 'ተከታዮች',
      'following': 'እየተከተሉ ያሉ',
      'posts': 'ልጥፎች',
      'theme': 'ገጽታ',
      'settings': 'ቅንብሮች',
      'openAdminDashboard': 'የአስተዳዳሪ ዳሽቦርድ ክፈት',
      'loadMore': 'ተጨማሪ አስጫን',
      'home': 'መነሻ',
      'search': 'ፈልግ',
      'post': 'ለጥፍ',
      'withCaption': 'ከመግለጫ ጋር',
      'withImage': 'ከምስል ጋር',
      'connectionsFilter': 'የግንኙነት ማጣሪያ',
      'allPeople': 'ሁሉም ሰዎች',
      'withBio': 'ባዮ ያለው',
      'withProfilePhoto': 'የፕሮፋይል ፎቶ ያለው',
    },
  };
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      AppLocalizations.supportedLocales.any((supported) =>
          supported.languageCode == locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return SynchronousFuture(AppLocalizations(locale));
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) => false;
}
