// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg0P2opiKIinGm39_GRL-TxZ-YibkL1Pk',
    appId: '1:87924268460:android:0e40d5a82819d75250ee09',
    messagingSenderId: '87924268460',
    projectId: 'picverse-1d8dd',
    storageBucket: 'picverse-1d8dd.firebasestorage.app',
  );

  // TODO: Run `flutterfire configure` to generate iOS config
  // After running, replace these placeholder values with real iOS config
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3nHt8dji8GtRGvyCy-6wwJJiSPMx2-hg',
    appId: '1:87924268460:ios:a312b92611e43aa750ee09',
    messagingSenderId: '87924268460',
    projectId: 'picverse-1d8dd',
    storageBucket: 'picverse-1d8dd.firebasestorage.app',
    iosBundleId: 'com.picverse.picverse',
  );
}
